### ISSUE TITLE
ممتاز

### ISSUE THREAD

**Issue by dregypt** [ahmedellaban1/django-job-board#1]
مجهود محترم. انا طبيب برمجت برنامج من ٣ اعوام ورفعته علي استضافه ديجتال  هوست 
ملحوظات لو مركز له تخصصات مختلفه وكل واحد له رول وصلاحيات ولهم مدير وكل طبيب له سكرتير  ز
رفع قاعده بيانات الادويه المصريه وتحسين الوصفه
الامراض لها اكواد
تسجيل خدمات لها كود
دخل كل طبيب وكل مريض له حساب يدخل ويحجز اون لين يعرف تحاليله واشعه له
السكرتير يحجز مواعيد لكل طبيب  ويرسل بالموبيل للمريض
كان عندي مشكله كيف اكتب او ارسم علي صوره المرض علي الجلد  لان البايثون وكانفس صعب شويه ا

**Comment by dregypt** [comment]
كل حجز يظهر علي شاشه للمرضي بالانتظار
عمل كيو ار كود لكل مريض ويمكن مسحه بالفون
دخول المرضي وعمليات داخل المركز
مستهللك ومخزن. ورواتب  الخ

**Comment by ahmedellaban1** [comment]
انا معنديش خبرة في الجزئية دي لكن من السرش ف اعتقد كل الحجات المتعلقه بتعديل الصور هتكون JS
تقدر تعمل سرش على 
Fabric.js
CamanJS
